spring:
  application:
    name: ms-notification
  datasource:
    url: jdbc:mysql://localhost:3306/challenge
    username: anakin
    password: hellothere
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: localhost
    username: anakin
    password: hellothere
  mail:
    host: smtp.gmail.com
    port: 587
    username: ******@gmail.com
    password: ***************
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

server:
  port: 8800

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
