services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: osjedipassword
      MYSQL_DATABASE: challenge
      MYSQL_USER: anakin
      MYSQL_PASSWORD: hellothere
