spring:
  application:
    name: ms-products
  datasource:
    url: jdbc:mysql://localhost:3306/challenge
    username: anakin
    password: hellothere
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: localhost
    username: anakin
    password: hellothere
server:
  port: 8200
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka