INSERT INTO tb_category(`id`,`name`)
VALUES
    (1, 'Electronics'),
    (2, 'Mobile Phones'),
    (3, 'Computers'),
    (4, 'Cameras'),
    (5, 'Headphones'),
    (6, 'Appliances'),
    (7, 'Beauty Products'),
    (8, 'Fashion'),
    (9, 'Footwear'),
    (10, 'Sports Equipment'),
    (11, 'Gaming Consoles'),
    (12, 'Home Decor'),
    (13, 'Kitchen Appliances'),
    (14, 'Outdoor Gear'),
    (15, 'Luggage and Travel Accessories'),
    (16, 'Personal Care'),
    (17, 'Cleaning Products'),
    (18, 'Batteries and Power'),
    (19, 'Audio Equipment'),
    (20, 'Watches'),
    (21, 'Health and Fitness'),
    (22, 'Smart Home Devices'),
    (23, 'TV and Entertainment'),
    (24, 'Streaming Devices'),
    (25, 'Home Security'),
    (26, 'Office Supplies'),
    (27, 'Software and Applications'),
    (28, 'Home Theater Systems'),
    (29, 'Tablets and E-readers'),
    (30, 'Image Hosting Services');